spring.application.name=weschedule

# ==================== BASE DE DONNÉES ====================
spring.datasource.url=jdbc:mysql://localhost:3306/weshedule?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==================== HIBERNATE / JPA ====================
spring.jpa.hibernate.ddl-auto=create-drop
# update ? crée/modifie les tables automatiquement
# (plus tard, mettre "validate" en production)

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Pour voir les logs Hibernate
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
